apiVersion: v1
kind: Service
metadata:
  name: laratchet-service
  labels:
    app: laratchet
spec:
  selector:
    app: laratchet
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
    - name: websocket
      protocol: TCP
      port: 3909
      targetPort: 9090
      nodePort: 30909 
    # - name: http
    #   protocol: TCP
    #   port: 3080
    #   targetPort: 80
    #   nodePort: 30909
  type: LoadBalancer